### ISSUE TITLE
Hard to tell exactly what this is...

### ISSUE THREAD

**Issue by naclcaleb** [byteble/byteble.github.io#1]
I see you invited me, but I don't know what this exactly is though. Care to explain?

**Comment by rocketbear27** [comment]
Basically, I got this idea from [Amazon Prime Air](https://www.amazon.com/Amazon-Prime-Air/b?ie=UTF8&node=8037720011) and [Amazon Scout](https://blog.aboutamazon.com/transportation/meet-scout). It is to deliver USB packages with software in the USB, using IoT devices. Its like Amazon except for physical USB software.

**Comment by rocketbear27** [comment]
We create robots that deliver people's software with a USB. Do you think it is a good idea?

**Comment by naclcaleb** [comment]
Yea, it sounds like it might be a good idea, but pretty complex and expensive don't you think?

It seems you want autonomous cars?

**Comment by rocketbear27** [comment]
For the area we have to cover, for now, is going to be a diameter of about 100 feet. We can use drones for auto-driven and short distances.

**Comment by naclcaleb** [comment]
Ok, so we're only covering about a 50-foot radius for now?

So far, it doesn't seem like we're leaving a house at all...

That also brings up another problem. GPS is only so accurate. Especially in such a small area, we need to have extremely accurate GPS in order to get to the right person.

**Comment by rocketbear27** [comment]
We could use coordinates for finding a specific person and place.

**Comment by naclcaleb** [comment]
But the robot has to know it's own coordinates...

In a small area, you might be able to use a beacon system, but that's not very scalable.

**Comment by rocketbear27** [comment]
Depending on our board, we could use [geopy](https://pypi.org/project/geopy/) for Raspberry Pi

**Comment by naclcaleb** [comment]
Potentially, yes. I've never used it, so I don't know how accurate it is. 

It uses addresses, though, and with a 50-ft radius we're still pretty much within the range of a single address.

**Comment by rocketbear27** [comment]
Is their such thing as geolocation in Arduino? We could use Johhney Five to use javascript, and javascript allows geolocation.

**Comment by naclcaleb** [comment]
There are various GPS modules and shields for Arduino and other microcontrollers.

**Comment by rocketbear27** [comment]
This is my first time tinkering with IoT. Should I buy Arduino Uno, or something like that because it has a GPS module, motors, LED's and more? To start the project.

**Comment by naclcaleb** [comment]
I think you might want to think it through a little more first. 

What do you think is the best delivery method? Drones, driving robots, or other?

How can you manage to make a profit? Is it too expensive to build autonomous robots for this, especially when the cost of a USB + Software can't be very high?

Is there a market for this? Generally, it might be easier just to put software on a usb yourself than to have a robot deliver it to you.

Just some questions to think about. Then you need to make a project design. Then you can start worrying about parts.

**Comment by rocketbear27** [comment]
We could have drones, driving robots, and remote controlled cars (just in case everything else fails).

We can program a robot to be autonomous. Users must buy a USB, write files and software on it, and pay a fee for shipping (for example, __ cents for __ feet). They can also send mail and small packages with a fee.

**Comment by naclcaleb** [comment]
Where are they delivering the USBs to?

**Comment by rocketbear27** [comment]
One user to another user

**Comment by rocketbear27** [comment]
our "post office" will only be open a few days a week. If it is an urgent package, people will pay extra.

**Comment by naclcaleb** [comment]
And...what would their incentive be to sending it through our system instead of using email or dropbox or something?

**Comment by rocketbear27** [comment]
Our system would be faster and more reliable because we are delivering actual packages. Our competitor would be the post office.

**Comment by naclcaleb** [comment]
If you think about it, that's basically how software was transported pre-internet, minus the autonomous robots.

**Comment by rocketbear27** [comment]
Our packages could include, mail, USB, and other little important packages.

**Comment by naclcaleb** [comment]
You don't have to answer this, but where are you (location)? Just curious.

**Comment by rocketbear27** [comment]
Maybe, instead of mailing system. We could create solutions for people's homes or rooms to increase productivity.

**Comment by naclcaleb** [comment]
Perhaps. 

Me too!

**Comment by rocketbear27** [comment]
The new objective of this orginization is to create IoT projects and DIY projects

**Comment by naclcaleb** [comment]
Ok

**Comment by naclcaleb** [comment]
In that case, I'd recommend Arduino, Raspberry Pi, Raspberry Pi Zero W, and the ESP8266 board.

**Comment by naclcaleb** [comment]
I'll stay for now, but I'm kind of busy working on a complete rewrite of my app.
